language: python
python:
- "3.6.1"
install: 
- pip install -r requirements.txt
- pip install coveralls
script: nosetests --with-coverage --cover-package=api && coverage report 
services:
  - postgresql
before_script:
  - psql -c 'create database weConnect_test;' -U postgres
  #- psql -c "CREATE USER postgres WITH PASSWORD 'mypassword';" -U postgres
  #- psql -c "GRANT ALL PRIVILEGES ON DATABASE weConnect_test to postgres;" -U postgres

after_success: 
- coveralls

addons:
  postgresql: "9.6"