language: python
python:
- "3.6"
install: pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database weConnect_V2_db;' -U postgres

script: nosetests --with-coverage 

after_success: coveralls