language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database weConnect_test;' -U postgres

script:
  - nosetests --exe -v --with-coverage

after_success:
- coveralls