language: python
python:
- "3.6"
install: pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE weConnect_test;' -U postgres
  #- psql -c "CREATE USER postgres WITH PASSWORD 'mypassword';" -U postgres
  - psql - c "GRANT ALL PRIVILEGES ON DATABASE weConnect_test to postgress;", -U postgres

script: nosetests --with-coverage --cover-package=tests/ && coverage report 

after_success: coveralls