language: python
python:
  - "3.6"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  #- psql -c 'create database postgres;' -U postgres

script:
  - nosetests --with-coverage --cover-package=tests/

after_success:
- coveralls