"""empty message

Revision ID: 268d95fe4be0
Revises: 
Create Date: 2018-06-25 11:58:47.315055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268d95fe4be0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'business_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('business_test', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
