"""empty message

Revision ID: c0c58b8ceca4
Revises: 1bb8dbc9d427
Create Date: 2018-05-17 12:10:58.961906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c58b8ceca4'
down_revision = '1bb8dbc9d427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('business_location', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'business_location')
    # ### end Alembic commands ###
