"""empty message

Revision ID: c2045793a6bb
Revises: 
Create Date: 2018-05-10 22:37:33.534995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2045793a6bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business', sa.String(length=50), nullable=True),
    sa.Column('biz_description', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('business_categ_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_categ_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=50), nullable=True),
    sa.Column('reviewer', sa.String(length=50), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['reviewer'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('businesses')
    # ### end Alembic commands ###
